config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#front'

  resources :users, only: [:create]
  get 'register', to: 'users#new'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'
  get 'home', to: 'locations#index'

  resources :locations
  resources :sessions, only: [:create, :destroy]
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :address
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email, :password, :full_name
  validates_uniqueness_of :email
  has_secure_password
  has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def require_user
    if !current_user
      flash[:error] = "Please log in."
      redirect_to sign_in_path unless current_user
    end
  end

  def current_user
    current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :require_user
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :require_location_creator, only: [:edit, :update, :destroy]

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user

    if @location.save
      flash[:notice] = "Your location has been created!"
      redirect_to home_path
    else
      flash[:error] = "Please fix the following errors."
      render :index
    end
  end

  def index
    @location = Location.new
    @locations = current_user.locations
  end

  def show
  end

  def edit
  end

  def update
    @location.address = location_params[:address]

    if @location.save
      flash[:success] = "The address has been updated successfully!"
      redirect_to location_path(@location)
    else
      flash[:error] = "Please fix the following errors."
      render :edit
    end
  end

  def destroy
    if @location.destroy
      flash[:notice] = "Address has been deleted successfully"
      redirect_to home_path
    end
  end

  private
    def location_params
      params.require(:location).permit(:address)
    end

    def set_location
      @location = Location.find(params[:id])
    end

    def require_location_creator
      unless current_user == @location.user
        flash[:error] = "You are not allowed to do that."
        redirect_to home_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to home_path if current_user
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to home_path, notice: "Welcome #{user.full_name}! You are signed in."
    else
      flash[:error] = "Invalid email or password"
      redirect_to sign_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are now logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome! You have registered successfully."
      redirect_to home_path
    else
      flash[:error] = "Please fix the following errors."
      render :new
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:email, :password, :full_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def index_map_link
    markers_array = []

    @locations.each do |location|
      markers_array << "&markers=#{location.latitude},#{location.longitude}"
    end

    markers_string = markers_array.join
    "http://maps.google.com/maps/api/staticmap?size=640x640#{markers_string}"
  end

  def single_location_map_link
    "http://maps.google.com/maps/api/staticmap?size=640x480&sensor=false&zoom=16&markers=#{@location.address}"
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title Map It - Map what you want!
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    %header
      = render 'shared/header'
    %section.content.clearfix
      = render 'shared/messages'
      = yield
    %footer
      &copy 2015 #{link_to 'Tom Lee', 'http://github.com/tomtl'}

app/views/locations/edit.html.haml
%section.my_queue.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          = bootstrap_form_for @location do |f|
            = f.text_field :address
            = f.submit "Update address"

app/views/locations/index.html.haml
%section.my_queue.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %h2 My Locations
          %table.table
            %thead
              %tr
                %th(width="50%") Address
                %th(width="25%") Latitude
                %th(width="25%") Longitude
            %tbody
              - @locations.each do |location|
                %tr
                  %td= link_to(location.address, location_path(location))
                  %td= location.latitude
                  %td= location.longitude
          = bootstrap_form_for(@location, layout: :horizontal) do |f|
            = f.text_field :address, label: "Add new address:", control_col: "col-sm-3"
            = f.submit "Add address"
          %br
          %p= image_tag index_map_link

app/views/locations/show.html.haml
%section.my_queue.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          %h2= @location.address
          %p= image_tag single_location_map_link
          %p= link_to 'Edit address', edit_location_path(@location), class: 'btn btn-primary'
          = link_to 'Delete address', location_path(@location), method: 'delete', class: 'btn btn-danger'

app/views/pages/front.html.haml
%section.site_title
  %h1
    Make the maps you want!
    = link_to "Sign Up Now!", register_path
  %p.sign_up
  %p.sign_in
    Have an account? Please
    = link_to "Sign In", sign_in_path

%section.container
  .row.title.h3
    .small-12.column
      %h6 Map It - My practice project.
  .row
    .large-12.column
      %p Map It allows users to plot addresses on a map. Addresses can be saved and used later. 
      %p The application makes use of the Geocoder gem and the Google Static Maps API. It is an original app created independantly from scratch.
      %p Demo Account: username: tom@example.com password: password
      %p
      #{link_to "Source Code:", "https://github.com/tomtl/mapit"} Ideas/Contributions are welcome

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    = link_to "Map It", home_path
  %form.navbar-form(action="")
    .form-group
    - if current_user
      .btn-group.nav_item.col-md-4
        = link_to "My Locations", locations_path
    - if current_user
      .btn-group.nav_item.col-md-6
        = link_to('', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown') do
          = current_user.full_name
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to sign_out_path do
              %i.icon-circle-arrow-left
              logout
    - unless current_user
      .btn-group.nav_item
        = link_to "Sign Up", register_path, class: 'btn btn-primary'
      .btn-group.nav_item
        = link_to "Sign In", sign_in_path, class: 'btn btn-primary'

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/users/new.html.haml
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-6") do |f|
        %header
          %h1 Register
        %fieldset
          = f.email_field :email, label: "Email Address"
          = f.password_field :password
          = f.text_field :full_name, label: "Full Name"
        %fieldset.actions.control-group.col-sm-offset-2
          .controls
            = f.submit "Sign Up"